apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: avalanche
  template:
    metadata:
      annotations:
        avalanche/scrape: "true"
      labels:
        name: avalanche
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  name: avalanche
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - --metric-count=2000
            - --series-count=100
            - --label-count=10
            - --value-interval=30
            - --metric-interval=604800 #every 7 days
            - --series-interval=86400 # every 24 hours (new)
          image: quay.io/freshtracks.io/avalanche:latest
          imagePullPolicy: IfNotPresent
          name: avalanche-metrics
          ports:
            - containerPort: 9001
              hostPort: 9001
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 1Mi
      serviceAccount: agent
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - configMap:
            name: prometheus-config
          name: prometheus-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 5
